<?php

namespace Mongobox\Bundle\JukeboxBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoGroupRepository extends EntityRepository
{
	public function findLast($maxResults, $group)
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();

		$qb->select('vg')
		->from('MongoboxJukeboxBundle:VideoGroup', 'vg')
		->where("vg.group = :group")
		->orderBy('vg.lastBroadcast', 'DESC')
		->setMaxResults($maxResults)
		->setParameters( array(
				'group' => $group
		));

		$query = $qb->getQuery();
		return $query->getResult();
	}
}