<?php

namespace Mongobox\Bundle\JukeboxBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideosRepository extends EntityRepository
{
    public function next()
    {
        $q = $this
                ->createQueryBuilder('v')
                ->select('v')
                ->where('v.done = 0')
                ->orderBy('v.date', 'ASC')
                ->setMaxResults(1)
                ->getQuery()
        ;

        $result = $q->getOneOrNullResult();

        //Si il n'y en a plus à passer, on fait un random
        if (is_null($result)) {
            $result = $this->random();
        }

        return $result;
    }

    /**
     * Fonction de recherche des vidéos
     * 
     * @param unknown_type $search
     * @param unknown_type $page
     * @param unknown_type $limit
     * @param unknown_type $filters
     * @return unknown
     */
    public function search($search, $page, $limit, $filters )
    {
        $q = $this
                ->createQueryBuilder('v')
                ->select('v')
                ->orderBy('v.'. $filters['sortBy'], strtoupper($filters['orderBy']) )
                ->setMaxResults($limit)
                ->setFirstResult($limit * ($page-1));

        if (array_key_exists('title', $search)) {
            $q
                ->where('v.title LIKE :title')
                ->setParameter('title', '%'.$search['title'].'%');
        }
        
        
        $q = $q->getQuery();

        $result = $q->getResult();

        return $result;
    }

	public function findGroupAll($group)
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();

		$qb->select('v')
		->from('MongoboxJukeboxBundle:Videos', 'v')
		->innerJoin('v.video_groups', 'vg')
		->where("vg.group = :group")
		->setParameters( array(
				'group' => $group
		));

		$query = $qb->getQuery();
		return $query->getResult();
	}
}
