<?php

namespace Mongobox\Bundle\JukeboxBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    public function wipe($id_video)
    {
        $em = $this->getEntityManager();
        $query = $em
                ->createQuery('DELETE FROM MongoboxJukeboxBundle:Vote v WHERE v.video = :id_video' )
				->setParameter('id_video', $id_video)
        ;

        return $query->getResult();
    }

    public function sommeVotes($video)
    {
        $em = $this->getEntityManager();
        $query = $em
                ->createQuery('SELECT SUM(v.sens) FROM MongoboxJukeboxBundle:Vote v WHERE v.video = :id_video')
				->setParameter('id_video', $video->getId()  )
        ;
		
        $result = $query->getResult();
        if(is_null($result[0][1])) $somme = 0;
        else $somme = (int) $result[0][1];
        return $somme;
    }
    public function sommeAllVotes()
    {
        $em = $this->getEntityManager();
        $query = $em
                ->createQuery('SELECT v, SUM(v.sens) as total FROM MongoboxJukeboxBundle:Vote v GROUP BY v.video')
                ;
        $result = $query->getResult();
        $somme = array();
        foreach ($result as $r) {
            $somme[$r[0]->getVideo()->getId()] = $r['total'];
        }

        return $somme;
    }
}
