<?php

namespace Mongobox\Bundle\StatisticsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivityRepository extends EntityRepository
{
}
