<?php

namespace Mongoeat\Bundle\VoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DecisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecisionRepository extends EntityRepository
{
}
