<?php

namespace Emk\Bundle\JukeboxBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

use Emk\Bundle\JukeboxBundle\Entity\Playlist;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends EntityRepository
{
    public function next($max)
    {
        $q = $this
                ->createQueryBuilder('p')
                ->select('p')
                ->orderBy('p.random', 'ASC')
                ->addOrderBy('p.date', 'ASC')
                ->setMaxResults($max)
                ->getQuery()
        ;

        if($max == 1) $result = $q->getOneOrNullResult ();
        else $result = $q->getResult();
        return $result;
    }

    public function generate()
    {
        $continue= true;
        while (count($this->findAll()) < 10 AND $continue) {
            $random = $this->_em->getRepository('EmkJukeboxBundle:Videos')->random();
            if(is_null($random)) $continue = false;
            else {
                $playlist_add = new Playlist();
                $playlist_add->setVideo($random);
                $playlist_add->setRandom(1);
                $playlist_add->setDate(new \Datetime());
                $this->_em->persist($playlist_add);
                $this->_em->flush();
            }
        }
    }
}
