<?php

namespace Emk\Bundle\JukeboxBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoCurrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoCurrentRepository extends EntityRepository
{
    public function wipe()
    {
        $em = $this->getEntityManager();
        $query = $em
                ->createQuery('DELETE FROM EmkJukeboxBundle:VideoCurrent vc')
                ;

        return $query->getResult();
    }
}
