<?php

namespace Mongoeat\Bundle\RestaurantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
    public function findSortVotes($city = null)
    {
        $q = $this->createQueryBuilder('b')
            ->addSelect('COUNT(v.id) AS HIDDEN cou')
            ->leftJoin('b.votes','v')
            ->orderBy('cou','DESC')
            ->groupBy('b.id');

        if (!empty($city)) {
            $q  ->where('b.city = :city')
                ->setParameter('city',$city);
        }

        return $q;
    }
}
