<?php

namespace Mongobox\Bundle\StatisticsBundle\Entity\Repository\User;

use Doctrine\ORM\EntityRepository;
use Mongobox\Bundle\StatisticsBundle\Statistics\UserActivity;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    /**
     * Retrieves the list of connected and active users
     *
     * @return array
     */
    public function getActiveUsers()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $fromDate   = new \DateTime();
        $fromDate   = $fromDate->modify('-15 minutes');

        $qb
            ->select('activities')
            ->from('MongoboxStatisticsBundle:User\Activity', 'activities')
            ->innerJoin('MongoboxGroupBundle:Group', 'group')
            ->where('activities.typeId = :type')
            ->andWhere('activities.date >= :date_from')
            ->setParameters(array(
                'type'      => UserActivity::LAST_HEARTBEAT,
                'date_from' => $fromDate
            ))
            ->addOrderBy('activities.date', 'DESC')
            ->getQuery()
        ;

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
